### ISSUE TITLE
Automatic version bumping tools interpret suffix as pre-release versions

### ISSUE THREAD

**Issue by KevinSchwarzer** [mantis-tec/actions#27]
I ran into an issue when trying to set up [google-github-actions/release-please-action](https://github.com/google-github-actions/release-please-action) on [argos-supervisor-ros2](https://github.com/mantis-tec/argos-supervisor-ros2). The same issue will arise in the other ROS 2 package repositories, too.

The image tag in the Docker compose files are usually specified using the following format: `mantistechnologies/<repo_name>:<version>-<ros_distro>`. E.g., the current image tag on argos-supervisor-ros2 is `mantistechnologies/argos-supervisor-ros2:v0.14.0-foxy`. However, according to the [item 9 in the SemVer spec](https://semver.org/spec/v2.0.0.html#spec-item-9), everything following a hyphen after the PATCH version is considered a pre-release version. Hence, [google-github-actions/release-please-action](https://github.com/google-github-actions/release-please-action) identifies the version in the image tag to be a pre-release version and replaces that pre-release version with the new version. I.e., the following lines in the Docker compose file

```yaml
services:
  supervisor:
    image: ${IMAGE_TAG:-mantistechnologies/argos-supervisor-ros2:v0.14.0-foxy}
```

are changed automatically to

```yaml
services:
  supervisor:
    image: ${IMAGE_TAG:-mantistechnologies/argos-supervisor-ros2:v0.14.1}
```

if the PATCH version updates. Notice that the `-foxy` suffix is removed, because it's interpreted as a pre-release version. According to the SemVer spec, the pre-release version could be anything, as long as it follows after the hyphen after the PATCH version.

Therefore, I would propose to prepend the ROS 2 version, instead of post-pending. I.e., taking the example from above, the image tag would turn out to be `mantistechnologies/argos-supervisor-ros2:foxy-v0.14.0`.
